language: node_js
node_js:
    - "8"
git:
    submodules: false
before_install:
    - export CHROME_BIN=google-chrome-stable
before_script:
    - npm install
script:
    - npm run ci
dist: trusty
addons:
    chrome: stable
branches:
  only:
  - master
sudo: required
