type SettingsPathShortcut =
	| 'animation'
	| 'colorAssignment'
	| 'canvasSize'
	| 'color'
	| 'colorSet'
	| 'endLayer'
	| 'getTileOriginAndSize'
	| 'grid'
	| 'gridSize'
	| 'layer'
	| 'refreshCanvas'
	| 'renderTexture'
	| 'rotateViewAboutCanvasCenter'
	| 'startAnimationFrame'
	| 'stripeCount'
	| 'stripeCountContinuum'
	| 'stripePosition'
	| 'texture'
	| 'tile'
	| 'tileSize'
	| 'view'

export { SettingsPathShortcut }
