const CANVAS_SIZE = 1000
const UNIT = 1
const END_ITERATION = 32
const GRID_SIZE = 32
const SQUARE_SIZE = 160
const COLOR_A = "#fff"
const COLOR_B = "#000"
const FRAME_RATE = 1000 / 60
const STRIPE_COUNT = 4
const SWITCHEROO = false
const FLIP_GRAIN = false
const STRIPE_ROTATION = 0
const BASE_STRIPE_DIAGONAL = "MINOR" // "PRINCIPAL"
const GINGHAM_MODE = false
const GONGRAM = false

const STRIPE_STYLE = "STANDARD"
// const STRIPE_STYLE = "DERASTERIZED_BY_AREA"
// const STRIPE_STYLE = "SEGMENT_OF_HARMONIC_CONTINUUM_ACROSS_GRID"
// const STRIPE_STYLE = "FULL_HARMONIC_CONTINUUM_COMPRESSED_INTO_SINGLE_TILE"

export {
	CANVAS_SIZE,
	UNIT,
	END_ITERATION,
	GRID_SIZE,
	SQUARE_SIZE,
	COLOR_A,
	COLOR_B,
	FRAME_RATE,
	STRIPE_COUNT,
	SWITCHEROO,
	FLIP_GRAIN,
	STRIPE_ROTATION,
	BASE_STRIPE_DIAGONAL,
	GINGHAM_MODE,
	GONGRAM,
	STRIPE_STYLE
}