const CANVAS_SIZE = 1000
const UNIT = 1
const END_ITERATION = 32
const GRID_SIZE = 16
const SQUARE_SIZE = 160
const COLOR_A = "#fff"
const COLOR_B = "#000"
const FRAME_RATE = 1000 / 60
const STRIPE_COUNT = 4
const SWITCHEROO = false
const FLIP_GRAIN = false
const STRIPE_ROTATION = 0
const BASE_STRIPE_DIAGONAL = "MINOR" // "PRINCIPAL"
const GINGHAM_MODE = false

export {
	CANVAS_SIZE,
	UNIT,
	END_ITERATION,
	GRID_SIZE,
	SQUARE_SIZE,
	COLOR_A,
	COLOR_B,
	FRAME_RATE,
	STRIPE_COUNT,
	SWITCHEROO,
	FLIP_GRAIN,
	STRIPE_ROTATION,
	BASE_STRIPE_DIAGONAL,
	GINGHAM_MODE
}