const CANVAS_SIZE = 1000
const UNIT = 1
const END_ITERATION = 32
const GRID_SIZE = 16
const SQUARE_SIZE = 160
const COLOR_A = "WHITE"
const COLOR_B = "BLACK"
const FRAME_RATE = 1000 / 60
const STRIPE_COUNT = 4

export {
	CANVAS_SIZE,
	UNIT,
	END_ITERATION,
	GRID_SIZE,
	SQUARE_SIZE,
	COLOR_A,
	COLOR_B,
	FRAME_RATE,
	STRIPE_COUNT
}