// tslint:disable:max-file-line-count no-reaching-imports

export {
	createOverrideLeafNode,
	createOverrideNodes,
	effectToggleHandler,
	enableOrDisableAnimationControls,
	enableOrDisableOtherEffectToggles,
	frameInputHandler,
	getCurrentFrame,
	getOverrideLeafNode,
	getOverrideParentNode,
	isParentOfAnyOverridingChildren,
	overrideClearHandler,
	overrideInputHandler,
	pauseHandler,
	playHandler,
	rewindHandler,
	snapshotHandler,
	toggleOverrideParentOpen,
	updateCurrentFrame,
	updateDescriptions,
	updateOverrideLeafNode,
	updateOverrideNodes,

	OverrideLeafNode,
	OverrideNode,
	OverrideParentNode,
} from './controls/indexForTest'
export {
	appendOverride,
	attachHandlers,
	createCheckbox,
	createContext,
	createContexts,
	createDescription,
	createEffectToggle,
	createEffectToggles,
	createLabel,
	createOverrideClear,
	createOverrideId,
	createOverrideLeaf,
	createOverrideParent,
	formatSetting,
	parseOverrideId,
	saveBlobThroughAnchor,
	storeDomElements,
	updateOverrides,

	AppendOverrideParams,
	CreateOverrideParams,
	CreateOverrideTextParams,
	Dimensions,
	OverrideOptions,
	Px,
} from './dom/indexForTest'
export {
	animation,
	executeTile,
	callFunctionsPerSetting,
	cancelCurrentPattern,
	clearAnimationIntervalAndRemoveFromState,
	completeLayers,
	executeAnimation,
	executeGrid,
	executeLayer,
	executePattern,
	executeEffect,
	getCurrentLayer,
	grid,
	thisPatternHasNotBeenCanceled,
	updateProgress,

	AnimationParams,
	ExecuteLayerParams,
	ExecuteParams,
	ExecuteTileParams,
	PatternIdAsParam,
} from './execute/indexForTest'
export {
	createPath,
	clearContext,
	clearContexts,
	clearMixedDownContext,
	clipPath,
	fill,
	fillPath,
	getCurrentContext,
	mixDownContexts,
	resetClip,
	saveCanvas,
	setClip,
	setupMixedDownContext,
	setupRenderStyle,

	ERASE,

	Path,
	Pixel,
} from './render/indexForTest'
export {
	concatFullSettingPath,
	checkSettingForConflict,
	combineEffects,
	composeMainHoundstooth,
	composePatterns,
	deeperPath,
	effectsHaveConflicts,
	getEffectSetting,
	getPatternSettingOrCreatePath,
	initializeCurrentPatternFromBasePattern,
	mapOverPattern,
	patternsHaveConflicts,
	prepareFunctionObjectsPerSetting,
	resetMainHoundstooth,
	setupAvailableEffects,
	shouldRecurse,

	DEFAULT_ANIMATIONS_PATTERN,
	DEFAULT_BASE_PATTERN,
	DEFAULT_LAYERS_PATTERN,

	CheckSettingForConflictParams,
	ComposePatternsParams,
	FullSettingPath,
	GetEffectSetting,
	MapOverPatternParams,
	PatternsHaveConflictsParams,
	PrepareFunctionObjectsParams,
	SettingFunction,
	SettingFunctionObject,
	SettingPath,
	DeeperPathParams,
	SettingStep,
} from './setting/indexForTest'
export { appState } from './appState'
export {
	AppState,
} from './types'
import * as startUp from './startUp'
export {
	startUp,
}
export {
	DEFAULT_APP_STATE,
} from './defaults'
