import { NullarySideEffector } from '../../src/utilities/types'
import noop from './noop'
import Spy = jasmine.Spy

type MockContext = {
	beginPath: NullarySideEffector,
	moveTo: { (x: number, y: number): void },
	lineTo: { (x: number, y: number): void },
	closePath: NullarySideEffector,
	fill: NullarySideEffector,
	clip: NullarySideEffector,
	save: NullarySideEffector,
	restore: NullarySideEffector,
	clearRect: NullarySideEffector,
	canvas: HTMLCanvasElement | { toBlob: Spy },
	drawImage: NullarySideEffector,
	globalCompositeOperation: string,
	fillStyle: string,
	font?,
	arc?,
	arcTo?,
	bezierCurveTo?,
	ellipse?,
	quadraticCurveTo?,
	rect?,
	globalAlpha?,
	imageSmoothingEnabled?,
	lineCap?,
	lineDashOffset?,
	lineJoin?,
	lineWidth?,
	miterLimit?,
	msFillRule?,
	shadowBlur?,
	shadowColor?,
	shadowOffsetX?,
	shadowOffsetY?,
	strokeStyle?,
	textAlign?,
	textBaseline?,
	mozImageSmoothingEnabled?,
	webkitImageSmoothingEnabled?,
	oImageSmoothingEnabled?,
	createImageData?,
	createLinearGradient?,
	createPattern?,
	createRadialGradient?,
	drawFocusIfNeeded?,
	fillRect?,
	fillText?,
	getImageData?,
	getLineDash?,
	isPointInPath?,
	measureText?,
	putImageData?,
	rotate?,
	scale?,
	setLineDash?,
	setTransform?,
	stroke?,
	strokeRect?,
	strokeText?,
	transform?,
	translate?,
}

type BuildMockContext = { ({}?: { contextCallsOrder?, toBlobSpy? }): MockContext }

const buildMockContext: BuildMockContext = ({ contextCallsOrder = [], toBlobSpy = null } = {}) => ({
	beginPath: () => contextCallsOrder.push({ method: 'beginPath' }),
	moveTo: (x, y) => contextCallsOrder.push({ method: 'moveTo', x, y }),
	lineTo: (x, y) => contextCallsOrder.push({ method: 'lineTo', x, y }),
	closePath: () => contextCallsOrder.push({ method: 'closePath' }),
	fill: () => contextCallsOrder.push({ method: 'fill' }),
	clip: () => contextCallsOrder.push({ method: 'clip' }),
	save: () => contextCallsOrder.push({ method: 'save' }),
	restore: () => contextCallsOrder.push({ method: 'restore' }),
	clearRect: () => contextCallsOrder.push({ method: 'clearRect' }),
	canvas: { toBlob: toBlobSpy },
	drawImage: noop,
	globalCompositeOperation: '',
	fillStyle: '',
})

export default buildMockContext
