import { NullarySideEffector } from '../../src/utilities/types'
import Spy = jasmine.Spy

type MockContext = {
	beginPath: NullarySideEffector,
	moveTo: { (x: number, y: number): void },
	lineTo: { (x: number, y: number): void },
	closePath: NullarySideEffector,
	fill: NullarySideEffector,
	clip: NullarySideEffector,
	save: NullarySideEffector,
	restore: NullarySideEffector,
	clearRect: NullarySideEffector,
	canvas: HTMLCanvasElement | { toBlob: Spy },
	drawImage: NullarySideEffector,
	globalCompositeOperation: string,
	fillStyle: string,
	font?,
	arc?,
	arcTo?,
	bezierCurveTo?,
	ellipse?,
	quadraticCurveTo?,
	rect?,
	globalAlpha?,
	imageSmoothingEnabled?,
	lineCap?,
	lineDashOffset?,
	lineJoin?,
	lineWidth?,
	miterLimit?,
	msFillRule?,
	shadowBlur?,
	shadowColor?,
	shadowOffsetX?,
	shadowOffsetY?,
	strokeStyle?,
	textAlign?,
	textBaseline?,
	mozImageSmoothingEnabled?,
	webkitImageSmoothingEnabled?,
	oImageSmoothingEnabled?,
	createImageData?,
	createLinearGradient?,
	createPattern?,
	createRadialGradient?,
	drawFocusIfNeeded?,
	fillRect?,
	fillText?,
	getImageData?,
	getLineDash?,
	isPointInPath?,
	measureText?,
	putImageData?,
	rotate?,
	scale?,
	setLineDash?,
	setTransform?,
	stroke?,
	strokeRect?,
	strokeText?,
	transform?,
	translate?,
}

export {
	MockContext,
}
